spring:
  datasource:
    url: jdbc:mysql://172.16.40.30:3306/baobao?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: org_api
    password: dinglicom
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
  jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/master.xml
    default-schema: baobao

wx:
  appId: wxe03f58cd79c2d8d9
  appSecret: cd5a7206a2ec333e5684628ffa06bf1f
  apiKey: vTHcW3eLDppmGZ8gIODRHlFKSyGd0TQ9
  mchId: 1488609932
  certPath: d:/apiclient_cert.p12
  createIp: 114.67.48.139
  notifyUrl: https://wx.aizhixin.com/open/v1/wxpay/notify
  tradeName: 包包大冒险-红包充值

pic:
  basePath: d:/tmp

server:
  tomcat:
    accesslog:
      enabled: true
      directory: d:/logs/
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: baobao_ris_access_log
      suffix: .log